### PR TITLE
Milestone 1, file structure

### PR DESCRIPTION
**Pull request by BenjaminGarza**

### CODE REVIEW

**Comment by maelfosso** [comment]
# Under review by Mael FOSSO

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @BenjaminGarza 

Thank you for this implementation of Git-Flow.
But please, I don't see anything into the `Feature` branch. The `bin/main.rb` file is empty.

What do you want to merge into the `Development` branch ?
What do you want to us the check, please ?

Don't hesitate to write me on Slack if you have any issues.
Thanks

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @BenjaminGarza 

Sorry, I didn't pay attention to the title of your pull request.
According to that, here are the changes I suggest you make

- [x] It's not *-bin-*, but `bin` without dash

- [x] He should also have a folder called `lib`

- [x] Please improve your README file. You should put a description of the project, the author's names with link to their Github profile

- [x] It's OK with the file `main.rb`

Kindly make those changes, please.
Thank you again.

**Review by Oghenebrume50 — APPROVED** [review]
Hi team this looks good now you can merge this branch and implement other milestones

**Pull request merged**
